# Iris

### Introduction:

This exercise may seem a little bit strange, but keep doing it.

### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).

### Step 3. Assign it to a variable called iris

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = pd.read_csv(url, header=None)
iris.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [24]:
iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
 4   4       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

### Step 4. Create columns for the dataset

In [25]:
iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### Step 5.  Is there any missing value in the dataframe?

In [ ]:
#check for missing values
iris.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

### Step 6.  Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

In [16]:
iris.loc[10:29, 2] = np.nan

### Step 7. Good, now lets substitute the NaN values to 1.0

In [ ]:
iris[2] = iris[2].fillna(1.0)

### Step 8. Now let's delete the column class

In [ ]:
iris = iris.drop('class', axis=1)

### Step 9.  Set the first 3 rows as NaN

In [32]:
iris.iloc[0:3] = np.nan

### Step 10.  Delete the rows that have NaN

In [20]:
iris = iris.dropna()

### Step 11. Reset the index so it begins with 0 again

In [21]:
iris = iris.reset_index(drop=True)

### BONUS: Create your own question and answer it.

In [22]:
# Bonus: What is the mean sepal length?
print("Mean sepal length:", iris['sepal_length'].mean())
print("\nFinal cleaned dataset shape:", iris.shape)
print("\nFirst few rows of the cleaned dataset:")
print(iris.head())

Mean sepal length: 5.862585034013605

Final cleaned dataset shape: (147, 5)

First few rows of the cleaned dataset:
   sepal_length  sepal_width  petal_length  petal_width    2
0           4.6          3.1           1.5          0.2  1.0
1           5.0          3.6           1.4          0.2  1.0
2           5.4          3.9           1.7          0.4  1.0
3           4.6          3.4           1.4          0.3  1.0
4           5.0          3.4           1.5          0.2  1.0